### ISSUE TITLE
feature: lazygit edit settings

### ISSUE THREAD

**Issue by suliatis** [folke/snacks.nvim#46]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

I'm experimenting with the lazygit snack, and when I want to edit a file via typing `e`, it opens the file in a buffer on a new tab.

### Describe the solution you'd like

I would like to set my own edit settings instead of using the `nvim-remote` preset because I rarely use tabs in my workflow.

### Describe alternatives you've considered

I checked the lazygit manual to see if it is possible to override a built-in preset in some way, but presets are baked into the source code.

### Additional context

The current config is:

```yaml
os:
  editPreset: "nvim-remote"
```

The default values for the `nvim-remote` are:

```yaml
os:
  edit: `[ -z "$NVIM" ] && (nvim -- {{filename}}) || (nvim --server "$NVIM" --remote-send "q" && nvim --server "$NVIM" --remote-tab {{filename}})`
  editAtLine: `[ -z "$NVIM" ] && (nvim +{{line}} -- {{filename}}) || (nvim --server "$NVIM" --remote-send "q" &&  nvim --server "$NVIM" --remote-tab {{filename}} && nvim --server "$NVIM" --remote-send ":{{line}}<CR>")`
  editAtLineAndWait: `nvim +{{line}} {{filename}}`
  openDirInEditor: `[ -z "$NVIM" ] && (nvim -- {{dir}}) || (nvim --server "$NVIM" --remote-send "q" && nvim --server "$NVIM" --remote-tab {{dir}})`
```

And I would like to change the `--remote-tab` to `--remote` everywhere to prevent creating new tabs.
